[project]
name = "python-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.0.3",
    "langchain-openai>=1.0.1",
    "openai>=2.6.1",
    "openai-agents>=0.4.2",
    "pylint>=4.0.2",
]
